name: Publish to Chromatic

inputs:
  github_token:
    description: 'Github access token'
    required: true
    type: string
  chromatic_project_token:
    description: 'The Chromatic API token'
    required: true
    type: string
  publish_chromatic:
    description: "If true, will publish to Chromatic. Otherwise will"
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    - name: chromatic_inputs
      shell: bash
      run: |
        echo "github_token=${{ inputs.github_token }}"
        echo "chromatic_project_token=${{ inputs.chromatic_project_token }}"
        echo "publish_chromatic=${{ fromJSON(inputs.publish_chromatic) }}"
    - name: chromatic_publish
      uses: chromaui/action@v1
      with:
        token: ${{ inputs.github_token }}
        projectToken: ${{ inputs.chromatic_project_token }}
        onlyChanged: true
        # Automatically accepts all changes in Chromatic as this was already done in the PR stage.
        autoAcceptChanges: ${{ fromJSON(inputs.publish_chromatic) }}
        exitOnceUploaded: true
