name: Since each job runs in its own environment, this action is responsible for setting up the environment

runs:
  using: "composite"
  steps:
    - id: setup_node
      if: ${{ !env.TEST }}
      name: setup_node
      uses: actions/setup-node@v3
      with:
        node-version: 18.15.0
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    - id: npm_install
      if: ${{ !env.TEST }}
      name: npm_install
      run: npm ci
      shell: bash
