name: Since each job runs in its own environment, this action is responsible for setting up the environment

inputs:
  use_dev:
    description: 'If true, will install dev dependencies.'
    required: false
    type: boolean
    default: false

# All booleans in a composite action must leverage fromJSON to ensure the value are treated
# as booleans and not strings. See issue here: https://github.com/actions/runner/issues/1483

runs:
  using: "composite"
  steps:
    - id: setup_node
      if: ${{ !fromJSON(env.TEST) }}
      name: setup_node
      uses: actions/setup-node@v3
      with:
        node-version: 18.15.0
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    - id: npm_install_prod_deps
      if: ${{ !fromJSON(env.TEST) && fromJSON(inputs.use_dev) }}
      name: npm_install_with_dev
      run: npm ci --ignore-scripts
      shell: bash
    - id: npm_install_prod_and_dev_deps
      if: ${{ !fromJSON(env.TEST) && !fromJSON(inputs.use_dev)}}
      name: npm_install
      run: npm ci --ignore-scripts --omit=dev
      shell: bash
    # https://github.com/actions/setup-node/blob/v3/docs/advanced-usage.md#use-private-packages
    - name: npm_rebuild
      run: npm rebuild && npm run prepare --if-present
      shell: bash
