name: Since each job runs in its own environment, this action is responsible for setting up the environment

# All booleans in a composite action must leverage fromJSON to ensure the value are treated
# as booleans and not strings. See issue here: https://github.com/actions/runner/issues/1483

runs:
  using: "composite"
  steps:
    - id: setup_node
      if: ${{ !fromJSON(env.TEST) }}
      name: setup_node
      uses: actions/setup-node@v3
      with:
        node-version: 18.15.0
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    - id: npm_install
      if: ${{ !fromJSON(env.TEST) }}
      name: npm_install
      run: npm ci
      shell: bash
