openapi: 3.0.1
info:
  title: Github Workflows
  description: JupiterOne Organization-Wide GitHub Workflows.
  x-cortex-git:
    github:
      repository: JupiterOne/.github
  x-cortex-owners:
    - type: group
      name: JupiterOne/sre
  x-cortex-service-groups: tier-4
  x-cortex-tag: github workflows
