name: Runs validation on the repo

# All booleans in a composite action must leverage fromJSON to ensure the value are treated
# as booleans and not strings. See issue here: https://github.com/actions/runner/issues/1483

runs:
  using: "composite"
  steps:
    - name: setup_env
      if: ${{ !fromJSON(env.TEST) }}
      uses: ./.github/actions/frontend/setup_env
    - name: validate
      if: ${{ !fromJSON(env.TEST) }}
      shell: bash
      run: npm run validate:ci
    # Check if we should skip validating runtime types
    - name: remote_type_check_skip
      if: ${{ !fromJSON(env.TEST) }}
      shell: bash
      run: |
        if [[ $(git log -2 --pretty=format:'%s' | grep "\[skip remote-type-check\]")  ]]; then 
          echo "HAS_SKIP=true" >> $GITHUB_ENV
        fi
    - name: echo_has_skip
      shell: bash
      run: echo "HAS_SKIP=${{ env.HAS_SKIP }}"
    # Validate runtime types (if applicable)
    - name: remote_type_test
      if: ${{ !fromJSON(env.TEST) && !env.HAS_SKIP }}
      shell: bash
      run: |
        npx -p @jupiterone/web-tools-remote-types@latest remote-types test
        echo "No breaking changes found";

