name: Slack Send
description: 'Send a message to the provided Slack Channel'

runs:
  using: "composite"
  steps:
    - name: notify_slack
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
        channel-id: ${{ env.SLACK_CHANNEL_ID }}
        # For posting a simple plain text message
        slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}