name: Deploys a frontend npm package

inputs:
  use_esbuild:
    description: 'If using esbuild, ensure its required build scripts are run'
    required: false
    type: boolean
  auto_token:
    description: 'Used for publishing the GitHub release and creating labels'
    required: true
    type: string

# All booleans in a composite action must leverage fromJSON to ensure the value are treated
# as booleans and not strings. See issue here: https://github.com/actions/runner/issues/1483

runs:
  using: "composite"
  steps:
    - name: npm_release_inputs
      if: ${{ fromJSON(env.TEST) }}
      shell: bash
      run: |
        echo "auto_token=${{ inputs.auto_token }}"
    - name: setup_env
      if: ${{ !fromJSON(env.TEST) }}
      uses: ./.github/actions/frontend/setup_env
    # run the esbuild build scripts
    - name: esbuild
      run: npm rebuild esbuild
      if: ${{ fromJson(inputs.use_esbuild) && !fromJSON(env.TEST) }}
      shell: bash
    - name: build
      if: ${{ !fromJSON(env.TEST) }}
      run: npm run build
      shell: bash
    # TODO: This is where security should add a security code scan
    # This is only what will be shipped to production and not any
    # testing deps. Hopefully this will gives us an accurate listing
    # of our shipped risks
    # This should live in the runner by default
    - name: add_auto_to_globals
      run: npm install -g auto@10.37.4
      shell: bash
    - name: deploy_to_npm
      if: ${{ !fromJSON(env.TEST) }}
      env:
        GH_TOKEN: ${{ inputs.auto_token }}
      run: npx auto shipit
      shell: bash
