name: Gets the name of the pull request branch the comment belongs to.

outputs:
  name:
    value: ${{ steps.comment_branch.outputs.head_ref }}

runs:
  using: "composite"
  steps:
    - id: comment_branch
      name: comment_branch
      uses: xt0rted/pull-request-comment-branch@v2