name: Creates and deploys the magic url

inputs:
  aws_role:
    type: string
  aws_region:
    type: string
  aws_apps_bucket:
    type: string
  github_token:
    type: string
  migration_number:
    type: string
  
runs:
  using: "composite"
  steps:
    - id: setup_env
      name: setup_env
      uses: ./.github/actions/frontend/setup_env
    - id: npm_build
      name: npm_build
      shell: bash
      run: npm run build
    - id: configure_aws_credentials
      name: configure_aws_credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.aws_role }}
        role-session-name:
          ${{ github.event.repository.name }}-magic-url-role-session
        aws-region: ${{ inputs.aws_region }}
    - id: deploy_magic_url
      name: deploy_magic_url
      shell: bash
      # This bucket file location is static and editing it will break the Magic URL. This pushes the entire directory which includes the bundle and remote types if applicable
      run: |
        aws s3 sync deploy/dist s3://${{ inputs.aws_apps_bucket }}/static/manual-deploy/${{ github.event.repository.name }}@${{ inputs.migration_number }}/PR-${{ github.event.number }}/
    - id: show_magic_url
      name: show_magic_url
      uses: Sibz/github-status-action@v1
      with: 
        authToken: ${{ inputs.github_token }}
        state: 'success'
        context: 'Magic URL'
        description: "Use the 'Details' link to view this PR in dev"
        target_url: https://apps.dev.jupiterone.io${{ inputs.magic_url_route }}?magic2=%7B%22${{ github.event.repository.name }}%40${{ inputs.migration_number }}%22:%22PR-${{ github.event.pull_request.number }}%22%7D
        sha: ${{github.event.pull_request.head.sha || github.sha}}