name: Creates and deploys the magic url

inputs:
  github_token:
    description: 'Github access token'
    type: string
    required: true
  migration_number:
    description: 'The migration number defined in the root package.json'
    required: true
    type: string
  magic_url_route: 
    description: 'The relative route the magic url should go to'
    type: string
    default: '/'
  pr_number: 
    description: 'The number associated with the PR that is triggering this action'
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: magic_url_inputs
      shell: bash
      run: |
        echo "github_token=${{ inputs.github_token }}"
        echo "migration=${{ inputs.migration_number }}"
        echo "magic_url_route=${{ inputs.magic_url_route }}"
    - name: configure_aws_credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        # J1 AWS role with deploy permissions to dev
        role-to-assume: arn:aws:iam::564077667165:role/github-pull-request-role
        role-session-name:
          ${{ github.event.repository.name }}-magic-url-role-session
        aws-region: us-east-2
    - name: deploy_artifacts_to_s3
      shell: bash
      # This bucket file location is static and editing it will break the Magic URL. This pushes the entire directory which includes the bundle and remote types if applicable
      run: |
        aws s3 sync deploy/dist s3://apps.dev.jupiterone.io/static/manual-deploy/${{ github.event.repository.name }}@${{ inputs.migration_number }}/PR-${{ inputs.pr_number }}/
    - name: get_branch_of_pr
      id: get_branch_of_pr
      uses: xt0rted/pull-request-comment-branch@v2
    - name: show_magic_url_in_pr
      uses: myrotvorets/set-commit-status-action@v2.0.0
      with:
        sha: ${{ steps.get_branch_of_pr.outputs.head_sha }}
        token: ${{ inputs.github_token }}
        status: success
        context: 'Magic URL'
        targetUrl: https://apps.dev.jupiterone.io${{ inputs.magic_url_route }}?magic2=%7B%22${{ github.event.repository.name }}%40${{ inputs.migration_number }}%22:%22PR-${{ inputs.pr_number }}%22%7D