name: Version And Release

runs:
  using: "composite"
  steps:
    - id: get_package_version
      name: get_package_version
      shell: bash
      run: |
        echo "version=$(jq -r .version < package.json)" >> $GITHUB_OUTPUT
    - name: semver_versions
      id: semver_versions
      uses: 'WyriHaximus/github-action-next-semvers@v1'
      with:
        version: ${{ steps.get_package_version.outputs.version }}

    - name: set_patch_version
      shell: bash
      run: |
        echo "new_version=${{ steps.semver_versions.outputs.patch }}" >> "$GITHUB_ENV
    - name: set_minor_version
      if: contains(github.event.pull_request.labels.*.name, 'minor') 
      shell: bash
      run: |
        echo "new_version=${{ steps.semver_versions.outputs.minor }}" >> "$GITHUB_ENV
    
    - id: echo_new_version
      shell: bash
      run: |
        echo "new_version is $new_version"