name: Version And Release

runs:
  using: "composite"
  steps:
    - id: get_package_version
      name: get_package_version
      shell: bash
      run: |
        echo "version=$(jq -r .version < package.json)" >> $GITHUB_OUTPUT
    - id: echo_package_version
      shell: bash
      run: |
        echo "get_package_version is ${{ steps.get_package_version.outputs.version }}"
    - name: next_version
      id: next_version
      uses: 'WyriHaximus/github-action-next-semvers@v1'
      with:
        version: ${{ steps.get_package_version.outputs.version }}
    - id: echo_new_version
      shell: bash
      run: |
        echo "get_package_version is ${{ steps.next_version.outputs.patch }}"
    