name: Version And Release

runs:
  using: "composite"
  steps:
    - id: get_package_version
      name: get_package_version
      shell: bash
      run: |
        echo "version=$(jq -r .version < package.json)" >> $GITHUB_OUTPUT
    - name: semver_versions
      id: semver_versions
      uses: 'WyriHaximus/github-action-next-semvers@v1'
      with:
        version: ${{ steps.get_package_version.outputs.version }}
