name: Publishes a frontend npm package

inputs:
  auto_token:
    description: 'Used for publishing the GitHub release and creating labels'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: npm_publish_inputs
      shell: bash
      run: |
        echo "auto_token=${{ inputs.auto_token }}"
    - name: deploy_to_npm
      env:
        GH_TOKEN: ${{ inputs.auto_token }}
      # Running git config to avoid the following error: unable to auto-detect email address
      run: |
        git config --global user.email "automation@jupiterone.com"
        git config --global user.name "Automation"
        npx --yes -p auto@11 auto shipit
      shell: bash
