name: Promotes built Docker images to target environment registries for consumption

inputs:
  image-name:
    required: true
  image-tags:
    required: true
    description: A comma separated list of image tags to promote.
  source-account-id:
    required: false
    default: 081157560428
  source-region:
    required: false
    default: us-east-1
  destination-account-id:
    required: true
  destination-region:
    required: true

runs:
  using: "composite"
  steps:
    - name: configurate_source_account_aws_credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{ inputs.source-account-id }}:role/github-main-role
        role-session-name: main-role-session-${{ inputs.image-name }}
        aws-region: us-east-1
    - name: ecr_login
      uses: aws-actions/amazon-ecr-login@v2
    - name: pull_source_images
      shell: bash
      run: |
        docker pull 081157560428.dkr.ecr.us-east-1.amazonaws.com/terraform-deploy-slim-lts-0
        for tag in $(echo ${{ inputs.image-tags }} | sed "s/,/ /g"); do
          docker pull ${{ inputs.source-account-id }}.dkr.ecr.us.${{ inputs.source-region }}/${{ inputs.image-name }}:$tag
        done
    - name: configurate_destination_account_aws_credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{ inputs.destination-account-id }}:role/github-main-role
        role-session-name: main-role-session-${{ inputs.image-name }}
        aws-region: us-east-1
    - name: bootstrap_destination_ecr_registry
      uses: jupiterone/provision-cortex/.github/actions/create_ecr_repo@SRE-1479
      with:
        codeowner: SRE
        image-names: ${{ inputs.image-name }}
        project-name: provision-cortex
        target-environment: dev
    - name: copy_to_destination_registry
      shell: bash
      run: |
        for tag in $(echo ${{ inputs.image-tags }} | sed "s/,/ /g"); do
          docker buildx imagetools create \
            --tag ${{ inputs.destination-account-id }}.dkr.ecr.us.${{ inputs.destination-region }}/${{ inputs.image-name }}:$tag \
            ${{ inputs.source-account-id }}.dkr.ecr.us.${{ inputs.source-region }}/${{ inputs.image-name }}:$tag
        done
