name: Runs validation on a frontend npm package

inputs:
  use_esbuild:
    description: 'If using esbuild, insure its required build scripts are run'
    required: false
    type: string
    default: false

# All booleans in a composite action must leverage fromJSON to ensure the value are treated
# as booleans and not strings. See issue here: https://github.com/actions/runner/issues/1483

runs:
  using: "composite"
  steps:
    - name: setup_env
      if: ${{ !fromJSON(env.TEST) }}
      uses: ./.github/actions/frontend/setup_env
      with:
        use_dev: true
    - name: esbuild_initial
      run: npm rebuild esbuild
      shell: bash
      if: ${{ fromJSON(inputs.use_esbuild) && !fromJSON(env.TEST) }}
    - name: validate
      if: ${{ !fromJSON(env.TEST) }}
      run: npm run validate:ci
      shell: bash
    # Sanity check so we don't end up with bad builds in main
    - name: install
      if: ${{ !fromJSON(env.TEST) }}
      run: npm ci --ignore-scripts --omit=dev
      shell: bash
    - name: esbuild_secondary
      run: npm rebuild esbuild
      shell: bash
      if: ${{ fromJSON(inputs.use_esbuild) && !fromJSON(env.TEST) }}
    - name: npm_build
      if: ${{ !fromJSON(env.TEST) }}
      run: npm run build
      shell: bash