name: Runs Cortex related jobs for Frontend Projects

inputs:
  cortex_api_key:
    description: 'The key that allows us to push data to Cortex'
    type: string
    required: true


runs:
  using: "composite"
  steps:
    - name: cortex_inputs
      shell: bash
      run: |
        echo "cortex_api_key=${{ inputs.cortex_api_key }}"
    - name: push_to_cortex
      run: npx --yes -p @jupiterone/web-tools-platform-analytics@latest platform-analytics all
      shell: bash
      env:
        CORTEX_API_KEY: ${{ inputs.cortex_api_key }}
