name: This action is responsible for setting up the environment, configuring node and installing the necessary dependencies

inputs:
  use_dev:
    description: 'If true, will install dev dependencies.'
    required: false
    type: boolean
    default: false
  uses_private_npm_packages:
    description: 'Set to false if your repo only consumes public packages and does not have the NODE_AUTH_TOKEN set.'
    type: boolean
    default: true

runs:
  using: "composite"
  steps:
    - name: check_for_auth_token
      if: ${{ fromJSON(inputs.uses_private_npm_packages) && env.NODE_AUTH_TOKEN == '' }}
      shell: bash
      run: |
        echo "the secret \"NODE_AUTH_TOKEN\" has not been set"
        exit 1
    - name: setup_node
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    - name: npm_install_prod_deps
      if: ${{ fromJSON(inputs.use_dev) }}
      run: npm ci --ignore-scripts
      shell: bash
    - name: npm_install_prod_and_dev_deps
      if: ${{ !fromJSON(inputs.use_dev)}}
      run: npm ci --ignore-scripts --omit=dev
      shell: bash
    - name: npm_rebuild
      run: npm rebuild && npm run prepare --if-present
      shell: bash

