name:
  Default workflow for a runtime when a PR is merged to main triggering the
  deploy flow

on:
  workflow_call:
    inputs:
      fallback_runner:
        description:
          'If true will leverage ubuntu-latest, otherwise will fall back to the
          J1 in-house runner'
        default: false
        type: boolean
      publish_chromatic:
        description: 'If true, will publish to Chromatic'
        type: boolean
    secrets:
      NPM_TOKEN:
        description: 'A J1 npm.com Publish token'
        required: true
      CORTEX_API_KEY:
        description: 'A key that allows us to push data to Cortex'
        required: true
      CHROMATIC_PROJECT_TOKEN:
        description: 'A token that allows us to publish to Chromatic'
        required: false

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  validate:
    # Name targeted by branch protections, do not change
    name: Validate
    runs-on:
      ${{ (inputs.fallback_runner && 'ubuntu-latest') ||
      'scaleset-jupiterone-infra-arm64' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: setup_env
        uses: jupiterone/.github/.github/actions/setup_env@v3.0.51
        with:
          use_dev: true
      - name: remote_types_install
        uses: jupiterone/.github/.github/actions/frontend/runtime/remote_types_install@v3.0.51
      - name: validate
        uses: jupiterone/.github/.github/actions/validate@v3.0.51
      - name: build
        uses: jupiterone/.github/.github/actions/build@v3.0.51

  chromatic_publish:
    runs-on:
      ${{ (inputs.fallback_runner && 'ubuntu-latest') ||
      'scaleset-jupiterone-infra-arm64' }}
    needs: validate
    if: ${{ inputs.publish_chromatic }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup_env
        uses: jupiterone/.github/.github/actions/setup_env@v3.0.51
        with:
          use_dev: true
      - name: chromatic_publish
        uses: jupiterone/.github/.github/actions/frontend/chromatic@v3.0.51
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          chromatic_project_token: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          publish_chromatic: true
