name: Release

on:
  pull_request:

# on:
  # push:
    # branches:
      # - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Until we can leverage our self hosted runners, we have to install
      - name: download_auto
        run: |
          curl -vkL -o - https://github.com/intuit/auto/releases/download/v10.46.0/auto-linux.gz | gunzip > /usr/local/bin/auto && \
          chmod +x /usr/local/bin/auto; \
      - name: update_composite_tags
        run: |
          VERSION=`auto version`
          echo "version will be $VERSION"
          npm run update-composite-tags $VERSION
      - name: version_docker
        uses: ./.github/actions/version_docker
        with:
          github_token: ${{ secrets.AUTO_GITHUB_PAT_TOKEN }}