name: Test

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: true
          fetch-depth: 0
          token: ${{ secrets.AUTO_GITHUB_PAT_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: pr_labels
        id: pr_labels
        uses: joerick/pr-labels-action@v1.0.8
      - name: package_json
        id: package_json
        run: |
          echo "version=$(jq -r .version < package.json)" >> $GITHUB_OUTPUT
      - name: semver_versions
        id: semver_versions
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.package_json.outputs.version }}
      - name: patch_version
        run: |
          echo "NEW_VERSION=${{ steps.semver_versions.outputs.patch }}" >> $GITHUB_ENV
      - name: minor_version
        if: contains(steps.pr_labels.outputs.labels, 'minor')
        run: |
          echo "NEW_VERSION=${{ steps.semver_versions.outputs.minor }}" >> $GITHUB_ENV
      - name: major_version
        if: contains(steps.pr_labels.outputs.labels, 'major')
        run: |
          echo "NEW_VERSION=${{ steps.semver_versions.outputs.major }}" >> $GITHUB_ENV
      - name: new_major
        id: new_major
        run: |
          echo "version=[\"${steps.package_json.outputs.version//', '/\".\"}\"]" >> $GITHUB_OUTPUT
      - name: echo_version_info
        run: |
          echo "current version is ${{ steps.package_json.outputs.version }}"
          echo "new version will be ${{ env.NEW_VERSION }}"
          echo "major version will be ${{ steps.new_major.outputs.version }}"