name: PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  validate:
    # Name targeted by branch protections, do not change
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup_env
        uses: ./.github/actions/setup_env
        with:
          use_dev: true
          uses_private_npm_packages: false
      - name: validate
        uses: ./.github/actions/validate