name: Release

on:
  pull_request:

# on:
  # push:
    # branches:
      # - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write 
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0
          token: ${{ secrets.AUTO_GITHUB_PAT_TOKEN }}
      # Until we can leverage our self hosted runners, we have to install
      - name: download_auto
        run: |
          curl -vkL -o - https://github.com/intuit/auto/releases/download/v10.28.0/auto-linux.gz | gunzip > ~/auto
          chmod a+x ~/auto
      - name: update_composite_tags
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_GITHUB_PAT_TOKEN }}
        run: |
          ~/auto info