name: Internal Test

# on:
  # push:
    # branches:
      # - main
      
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm ci
      # Until we can leverage our self hosted runners, we have to install
      - name: download_auto
        run: |
          curl -vkL -o - https://github.com/intuit/auto/releases/download/v10.46.0/auto-linux.gz | gunzip > /usr/local/bin/auto && \
          chmod +x /usr/local/bin/auto; \
      - name: get_version
        id: get_version
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_GITHUB_PAT_TOKEN }}
        # VERSION=`auto version`
        run: |
          VERSION='v3.0.1'
          echo "version will be $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo $VERSION | cut -d '.' -f 1
          echo "major_version=$(echo $VERSION | cut -d '.' -f 1)" >> $GITHUB_OUTPUT
      - name: update_composite_tags
        run: |
          echo "update-composite-tags with ${{ steps.get_version.outputs.version }}"
          npm run update-composite-tags ${{ steps.get_version.outputs.version }}
      # - name: version_docker
      - name: update_major_tag
        run: |
          echo "update_major_tag with ${{ steps.get_version.outputs.major_version }}"
          