name: Find LaunchDarkly flag code references

on:
  workflow_call:
    inputs:
      PROJECT_KEY:
        description:
          LaunchDarkly project key, can be found at
          https://app.launchdarkly.com/settings/projects
        required: true
        type: string
    secrets:
      LD_ACCESS_TOKEN:
        description:
          Access token for LaunchDarkly. Security can add this to your
          repository
        required: true
# cancel in-flight workflow run if another push was triggered
concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 11 # This value must be set if the lookback configuration option is not disabled for find-code-references. Read more: https://github.com/launchdarkly/ld-find-code-refs#searching-for-unused-flags-extinctions
      - name: LaunchDarkly Code References
        uses: launchdarkly/find-code-references@v2.10.0
        with:
          accessToken: ${{ secrets.LD_ACCESS_TOKEN }}
          projKey: ${{ inputs.PROJECT_KEY }}
