name: Default workflow for a provision only repo when a PR is merged to main triggering the release flow

on:
  workflow_call:
    inputs:
      fallback_runner:
        description: "If true will leverage ubuntu-latest, otherwise will fall back to the J1 in-house runner"
        default: false
        type: boolean
    secrets:
      NPM_TOKEN:
        description: "A J1 npm.com Publish token"
        required: true
      AUTO_GITHUB_PAT_TOKEN:
        description: "This is a GitHuh PAT that let's auto write back to main after npm versioning"
        required: true

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  validate:
    # Name targeted by branch protections, do not change
    name: Validate
    runs-on: ${{ (inputs.fallback_runner && 'ubuntu-latest') || 'scaleset-jupiterone-infra-arm64' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: setup_env
        uses: jupiterone/.github/.github/actions/setup_env@v3.0.8
        with:
          use_dev: true
      - uses: hashicorp/setup-terraform@v2
      - name: validate
        uses: jupiterone/.github/.github/actions/validate@v3.0.8
  
  security:
    runs-on: ${{ (inputs.fallback_runner && 'ubuntu-latest') || 'scaleset-jupiterone-infra-amd64' }}
    permissions:
      actions: read
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: security
        uses: jupiterone/.github/.github/actions/code_ql@v3.0.8
        with:
          language: 'javascript'

  version_artifact:
    runs-on: ${{ (inputs.fallback_runner && 'ubuntu-latest') || 'scaleset-jupiterone-infra-amd64' }}
    needs: validate
    steps:
      - uses: actions/checkout@v3
      - name: version_artifact
        uses: jupiterone/.github/.github/actions/version_artifact@v3.0.8
        with:
          github_token: ${{ secrets.AUTO_GITHUB_PAT_TOKEN }}
