name: PR

on:
  pull_request:
    inputs:
      fallback_runner:
        description: "If true will levarege ubuntu-latest, otherwise will fall back to the J1 in-house runner"
        default: false
        type: boolean

jobs:
  pr:
    runs-on: ${{ (inputs.fallback_runner && 'ubuntu-latest') || fromJson('["jupiterone-dev", "arm64"]') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm ci
      - run: npm run validate